#undef PACKAGE
#undef VERSION

/* Gettext stuff */
#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY

#undef USE_GLIB2

#undef GNL_CONFIG_DIR

#undef HAVE_ATOMIC_H

#undef GST_DEBUG_ENABLED
#undef GST_INFO_ENABLED
#undef GST_DEBUG_COLOR

#undef GST_DISABLE_LOADSAVE
